# Generated by Django 2.2.10 on 2020-03-15 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200314_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='test', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
